name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整的 git 历史
    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v5.4.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        mode: 'COMMIT'
        configuration: 'changelog.configure.json'
    - name: Display Changelog
      run: echo "${{ steps.build_changelog.outputs.changelog }}"
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: nowsprinting/check-version-format-action@v3
      id: version
      with:
        prefix: 'v'
    - name: Build
      run: |
        VERSION=$(echo "${{ steps.version.outputs.full_without_prefix }}")
        pnpm install
        echo "VERSION=$VERSION pnpm build"
        VERSION="$VERSION" pnpm build
    - name: GH Release
      uses: softprops/action-gh-release@v2.3.2
      with:
          files: dist/huifu-aihelper.user.js
          generate_release_notes: true
          body: ${{steps.build_changelog.outputs.changelog}}
